---
- name: Configure Subscription Manager
  hosts: all
  gather_facts: yes
  become: yes

  tasks:
  - import_role:
      name: subscription-manager-register

- name: Configure HTTP Web Server
  hosts: all
  gather_facts: yes
  become: yes

  tasks:
  - import_role:
      name: httpd
